export const TEXTS = {
    SIGNUP: {
        title: "Sign Up",
        subtitle: "Sign up to create an account",
        fullNameLabel: "Full Name",
        fullNamePlaceholder: "John Doe",
        fullNameRequired: "Full name is required",
        emailLabel: "Email",
        emailPlaceholder: "Hs7oJ@example.com",
        emailRequired: "Email is required",
        passwordLabel: "Password",
        passwordPlaceholder: "Password",
        passwordRequired: "Password is required",
        phoneNumberLabel: "Phone No.",
        phoneNumberPlaceholder: "1234567890",
        phoneNumberRequired: "Phone number is required",
        countryCode: "IN +91",
        country: "Country",
        buttonTitle: "Sign Up",
        continueWith: "or continue with",
        footerText: "Do You have an account?",
        signIn: "sign in",
    },
    LOGIN: {
        title: "Login",
        subtitle: "Login to your account",
        emailLabel: "Email",
        emailPlaceholder: "Hs7oJ@example.com",
        emailRequired: "Email is required",
        passwordLabel: "Password",
        passwordPlaceholder: "Password",
        passwordRequired: "Password is required",
        buttonTitle: "Login",
        continueWith: "or continue with",
        footerText: "Don't have an account?",
        signUp: "sign up",
    },
}